"use client";

import { useState } from "react";

import {
  ArrowLeftIcon,
  CheckCircleIcon,
  FacebookIcon,
  KijijiIcon,
  PencilIcon,
  RocketIcon,
  SparkleIcon,
  TagIcon,
} from "@/components/Icons";
import {
  LISTING_CATEGORIES,
  LISTING_CONDITIONS,
  type ListingCategory,
  type ListingCondition,
} from "@/types/listing";
import type { GeneratedListing, Marketplace, UploadedPhoto } from "@/types/app";

type ReviewStepProps = {
  listing: GeneratedListing;
  photos: UploadedPhoto[];
  marketplaces: Marketplace[];
  onChange: (listing: GeneratedListing) => void;
  onSubmit: () => void;
  onBack: () => void;
};

const inputClass =
  "w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-900 focus:border-indigo-500 focus:outline-none focus:ring-4 focus:ring-indigo-100";

export default function ReviewStep({
  listing,
  photos,
  marketplaces,
  onChange,
  onSubmit,
  onBack,
}: ReviewStepProps) {
  const [isEditing, setIsEditing] = useState(false);
  const primaryPhoto = photos[0];

  return (
    <div className="vendio-step-enter mx-auto max-w-5xl px-6 pt-14 pb-20">
      <button
        type="button"
        onClick={onBack}
        className="inline-flex items-center gap-1.5 text-sm font-medium text-slate-500 transition hover:text-slate-900"
      >
        <ArrowLeftIcon className="h-4 w-4" />
        Back
      </button>

      <div className="mt-8 flex flex-col gap-2 text-center sm:text-left">
        <div className="inline-flex w-fit items-center gap-2 self-center rounded-full border border-indigo-100 bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700 sm:self-start">
          <SparkleIcon className="h-3.5 w-3.5" />
          Listing generated by Vendio
        </div>
        <h1 className="text-3xl font-semibold tracking-tight text-slate-900 sm:text-4xl">
          Step 3 of 3 — Review your listing
        </h1>
        <p className="text-base text-slate-600">
          Vendio drafted everything below. Approve it as-is, or tap Edit to make changes.
        </p>
      </div>

      <div className="mt-10 grid gap-6 lg:grid-cols-[1.15fr_1fr]">
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <header className="flex items-center justify-between">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                Listing details
              </p>
              <h2 className="mt-1 text-lg font-semibold text-slate-900">
                {isEditing ? "Editing draft" : "Generated draft"}
              </h2>
            </div>
            <button
              type="button"
              onClick={() => setIsEditing((value) => !value)}
              className={`inline-flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-semibold transition ${
                isEditing
                  ? "border-indigo-200 bg-indigo-50 text-indigo-700"
                  : "border-slate-200 bg-white text-slate-700 hover:bg-slate-50"
              }`}
            >
              <PencilIcon className="h-3.5 w-3.5" />
              {isEditing ? "Done editing" : "Edit Listing"}
            </button>
          </header>

          <div className="mt-6 space-y-5">
            <Field label="Title">
              {isEditing ? (
                <input
                  className={inputClass}
                  value={listing.title}
                  onChange={(event) => onChange({ ...listing, title: event.target.value })}
                />
              ) : (
                <p className="text-base font-semibold text-slate-900">{listing.title}</p>
              )}
            </Field>

            <div className="grid gap-5 sm:grid-cols-2">
              <Field label="Price">
                {isEditing ? (
                  <div className="relative">
                    <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-sm text-slate-400">
                      $
                    </span>
                    <input
                      type="number"
                      min={1}
                      className={`${inputClass} pl-7`}
                      value={listing.price}
                      onChange={(event) =>
                        onChange({ ...listing, price: Number(event.target.value) })
                      }
                    />
                  </div>
                ) : (
                  <p className="text-base font-semibold text-slate-900">${listing.price}</p>
                )}
              </Field>

              <Field label="Condition">
                {isEditing ? (
                  <select
                    className={inputClass}
                    value={listing.condition}
                    onChange={(event) =>
                      onChange({
                        ...listing,
                        condition: event.target.value as ListingCondition,
                      })
                    }
                  >
                    {LISTING_CONDITIONS.map((condition) => (
                      <option key={condition} value={condition}>
                        {condition}
                      </option>
                    ))}
                  </select>
                ) : (
                  <p className="text-base font-medium text-slate-900">{listing.condition}</p>
                )}
              </Field>
            </div>

            <Field label="Category">
              {isEditing ? (
                <select
                  className={inputClass}
                  value={listing.category}
                  onChange={(event) =>
                    onChange({
                      ...listing,
                      category: event.target.value as ListingCategory,
                    })
                  }
                >
                  {LISTING_CATEGORIES.map((category) => (
                    <option key={category} value={category}>
                      {category}
                    </option>
                  ))}
                </select>
              ) : (
                <p className="text-base font-medium text-slate-900">{listing.category}</p>
              )}
            </Field>

            <Field label="Description">
              {isEditing ? (
                <textarea
                  rows={8}
                  className={inputClass}
                  value={listing.description}
                  onChange={(event) =>
                    onChange({ ...listing, description: event.target.value })
                  }
                />
              ) : (
                <p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">
                  {listing.description}
                </p>
              )}
            </Field>
          </div>
        </section>

        <aside className="space-y-6">
          <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div className="aspect-[4/3] w-full bg-slate-100">
              {primaryPhoto ? (
                /* eslint-disable-next-line @next/next/no-img-element */
                <img
                  src={primaryPhoto.previewUrl}
                  alt={listing.title}
                  className="h-full w-full object-cover"
                />
              ) : null}
            </div>
            {photos.length > 1 ? (
              <div className="grid grid-cols-4 gap-1.5 p-2">
                {photos.slice(1, 5).map((photo) => (
                  /* eslint-disable-next-line @next/next/no-img-element */
                  <img
                    key={photo.id}
                    src={photo.previewUrl}
                    alt={photo.name}
                    className="aspect-square w-full rounded-md object-cover"
                  />
                ))}
              </div>
            ) : null}
            <div className="px-5 py-4">
              <div className="flex items-center justify-between">
                <p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                  Preview
                </p>
                <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700">
                  <CheckCircleIcon className="h-3.5 w-3.5" />
                  Ready
                </span>
              </div>
              <p className="mt-3 text-base font-semibold text-slate-900">{listing.title}</p>
              <p className="mt-1 flex items-center gap-1.5 text-2xl font-semibold tracking-tight text-slate-900">
                <TagIcon className="h-4 w-4 text-slate-400" />${listing.price}
              </p>
              <div className="mt-3 flex flex-wrap gap-1.5">
                <Chip>{listing.category}</Chip>
                <Chip>{listing.condition}</Chip>
                <Chip>
                  {photos.length} photo{photos.length === 1 ? "" : "s"}
                </Chip>
              </div>
            </div>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
              Posting to
            </p>
            <ul className="mt-3 space-y-2">
              {marketplaces.map((marketplace) => (
                <li
                  key={marketplace}
                  className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-3 py-2.5"
                >
                  {marketplace === "facebook" ? (
                    <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#1877F2]/10 text-[#1877F2]">
                      <FacebookIcon className="h-4 w-4" />
                    </span>
                  ) : (
                    <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-50 text-emerald-700">
                      <KijijiIcon className="h-4 w-4" />
                    </span>
                  )}
                  <p className="text-sm font-medium text-slate-900">
                    {marketplace === "facebook" ? "Facebook Marketplace" : "Kijiji"}
                  </p>
                </li>
              ))}
            </ul>
          </div>

          <button
            type="button"
            onClick={onSubmit}
            className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3.5 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-700"
          >
            <RocketIcon className="h-4 w-4" />
            Submit Listing
          </button>
          <p className="text-center text-xs text-slate-500">
            Vendio will fill the marketplace forms and publish on your behalf.
          </p>
        </aside>
      </div>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p>
      <div className="mt-2">{children}</div>
    </div>
  );
}

function Chip({ children }: { children: React.ReactNode }) {
  return (
    <span className="rounded-full bg-slate-100 px-2.5 py-0.5 text-xs font-medium text-slate-700">
      {children}
    </span>
  );
}
